apiVersion: 1
contactPoints:
  - orgId: 1
    name: default-alerts
    receivers:
      - uid: cp-email
        type: email
        settings:
          addresses: "josercdossantos@hotmail.com"
      - uid: cp-telegram
        type: telegram
        settings:
          bottoken: "${GRAFANA_TELEGRAM_BOT_TOKEN}"
          chatid: "54997004963"
route:
  receiver: default-alerts
  group_by: ["alertname"]
  routes: []
