apiVersion: 1
datasources:
  - name: InfluxDB
    type: influxdb
    access: proxy
    isDefault: true
    editable: true
    jsonData:
      version: Flux
      organization: planta
      defaultBucket: processo
      tlsSkipVerify: true
    secureJsonData:
      # Usa o token de leitura injetado via env GRAFANA_INFLUX_TOKEN
      token: ${GRAFANA_INFLUX_TOKEN}
