apiVersion: 1
datasources:
  - name: InfluxDB
    uid: influxdb
    type: influxdb
    access: proxy
    isDefault: true
    url: http://influxdb:8086
    jsonData:
      version: Flux
      organization: planta
      defaultBucket: processo
    secureJsonData:
      token: ${GRAFANA_INFLUX_TOKEN}
